Flag Path Update to remove "//"
GrandComicsDatabase/gcd-django pull request #617
Opened 2023-09-18 16:23 UTC by prutledge

Fix #616 - update creation of path url to remove double /

2023-09-18 16:33 UTC, LegalizeAdulthood commented
LGTM

2023-09-29 00:43 UTC, jochengcd requested changes

2023-09-29 00:43 UTC, jochengcd commented on apps/indexer/templates/indexer/bits/profile_display.html
> -  <li> Country: <img src="{{ STATIC_URL }}/img/gcd/flags/{{ profile_user.indexer.country.code|lower }}.png" alt="{{ country }}" class="embedded_flag">
You do have a working dev to test a change on the corresponding pages, right ?
Then we should do the full change here and replace
img src="{{ STATIC_URL }}/img/gcd/flags/{{ profile_user.indexer.country.code|lower }}.png" alt="{{ country }}" class="embedded_flag" (with the <> around)
by
{{ profile_user.indexer.country|show_country_flag }}
to have the code the generate the flag path only in one place
you might need to add
{% load credits %}
in the beginning of a template if not already there

2023-09-29 00:43 UTC, jochengcd commented on apps/indexer/templates/indexer/bits/profile_display.html
> +  <li> Country: <img src="{{ STATIC_URL }}img/gcd/flags/{{ profile_user.indexer.country.code|lower }}.png" alt="{{ country }}" class="embedded_flag">
same comment

2023-09-29 00:43 UTC, jochengcd commented on templates/gcd/admin/countries.html
> +    <img src="{{ STATIC_URL }}img/gcd/flags/{{ country.code|lower }}.png" alt=" " class="embedded_flag"> ({{ country.code|lower }}) {{ country }}<br/>
same comment

2023-09-29 00:43 UTC, jochengcd commented on templates/gcd/bits/series_issue_header.html
> +    <img src="{{ STATIC_URL }}img/gcd/flags/{{ series.country.code|lower }}.png" alt="{{ country }}" class="embedded_flag">
same comment

2023-09-29 00:43 UTC, jochengcd commented on templates/gcd/status/international_stats.html
> +            Statistics for Comics {% if type == 'country' %} published in <img style="vertical-align:middle" src="{{ STATIC_URL }}img/gcd/flags/{{ object.code|lower }}.png" alt="{{ object }}">{% else
here
src="{{ STATIC_URL }}img/gcd/flags/{{ object.code|lower }}.png" alt="{{ object }}"
by
{{ object|show_country_info_by_code }}

2023-10-09 21:46 UTC, jochengcd commented
If you don't want to do the code cleanup, this is fine as well. 
But, usually we should aim to cleanup code when doing changes at places. This is a case for a supporting routine implemented at some point, but not brought into play in all places were it could have been used.

2023-11-13 18:27 UTC, merged